// Registro delle demo. Una voce per demo: la galleria e il guscio comune leggono solo da qui.
// id = nome della cartella in demo/ e dei suoi file (demo/<id>/<id>.html, <id>.js).
window.STILI = [
  // ───────────────────────────── 3D ─────────────────────────────
  { id: 'cel', dim: '3D', titolo: 'Cel shading',
    ispirazione: 'The Legend of Zelda: The Wind Waker',
    descrizione: 'Un\'isola tropicale al tramonto disegnata come un cartone animato: luce a gradini, contorni d\'inchiostro, mare con la schiuma a strisce.',
    tecnica: 'Rampa di luce a tre gradini nello shader, contorno a guscio rovesciato, luce di bordo, acqua con schiuma calcolata dalla profondità.',
    controlli: 'WASD per camminare · Maiusc per correre · trascina per girare la visuale · rotella per lo zoom' },
  { id: 'voxel', dim: '3D', titolo: 'Voxel',
    ispirazione: 'Minecraft, Teardown, MagicaVoxel',
    descrizione: 'Un\'isola sospesa fatta di cubetti, da scavare e ricostruire.',
    tecnica: 'Mesh generata per blocchi con le sole facce visibili, occlusione ambientale per vertice, ombre morbide.',
    controlli: 'Trascina per girare · clic sinistro scava · clic destro costruisce · 1-5 sceglie il blocco · rotella per lo zoom' },
  { id: 'lowpoly', dim: '3D', titolo: 'Low poly atmosferico',
    ispirazione: 'Firewatch',
    descrizione: 'Una valle di boschi a facce piatte, colorata dalla foschia come un poster anni \'70.',
    tecnica: 'Facce piatte, prospettiva aerea che tinge i piani per distanza e quota, cielo dipinto con un grande sole, una sola tavolozza che cambia con l\'ora.',
    controlli: 'Trascina per girare · rotella per lo zoom · ↑↓ per cambiare l\'ora' },
  { id: 'foto', dim: '3D', titolo: 'Fotorealistico',
    ispirazione: 'Rendering di prodotto, archviz',
    descrizione: 'Una natura morta su un tavolo di legno: ottone, ceramica smaltata, vetro con il vino, frutta, lino.',
    tecnica: 'Materiali PBR e modelli fotografati (Poly Haven), luce da HDRI, occlusione ambientale; appena la camera si ferma i fotogrammi si accumulano spostando di poco camera, obiettivo e luce: antialias, profondità di campo e ombre morbide vere.',
    controlli: 'Trascina per girare · rotella per lo zoom · H cambia ambiente (4)' },
  { id: 'ps1', dim: '3D', titolo: 'PlayStation 1',
    ispirazione: 'Silent Hill, Resident Evil, i primi anni del 3D',
    descrizione: 'Un villaggio nella nebbia con i difetti che facevano l\'epoca: vertici che tremano e texture che si torcono.',
    tecnica: 'Schermo di 240 righe ingrandito senza filtro, vertici agganciati ai pixel, texture affini senza correzione prospettica, luce e nebbia calcolate per vertice, colore a 15 bit col retino di dithering della console.',
    controlli: 'WASD per muoversi · mouse per guardare · F accende la torcia · Maiusc per correre' },
  { id: 'vettori3d', dim: '3D', titolo: 'Vettoriale 3D',
    ispirazione: 'Battlezone (1980)',
    descrizione: 'Un campo di battaglia a fil di ferro verde fosforo, con i poligoni nascosti e il bagliore del tubo catodico.',
    tecnica: 'Spigoli su corpi neri che nascondono le linee dietro, bagliore, persistenza del fosforo, vetro curvo e la pellicola rossa e verde del cabinato.',
    controlli: 'W S avanti e indietro · A D girano il carro · spazio per sparare' },
  { id: 'obradinn', dim: '3D', titolo: '1 bit',
    ispirazione: 'Return of the Obra Dinn',
    descrizione: 'Il ponte di una nave disegnato con due soli colori, come un\'incisione su un vecchio Macintosh.',
    tecnica: 'Luce ridotta a due colori con un rumore blu incollato alle direzioni del mondo (girando la testa non sfarfalla), contorni da salti di profondità e pieghe delle superfici, sartiame disegnato come linee.',
    controlli: 'WASD per muoversi · mouse per guardare · H cambia i colori' },
  { id: 'moebius', dim: '3D', titolo: 'Ligne claire',
    ispirazione: 'Moebius, Sable',
    descrizione: 'Un deserto di rovine disegnato a china e colori piatti, come una tavola a fumetti francese.',
    tecnica: 'Contorni a china ricavati da profondità e normali, colori piatti a due toni, tratteggio ancorato al mondo che cambia scala con la distanza, sbuffi di polvere a fumetto.',
    controlli: 'WASD per guidare · clic e mouse per girare la visuale · rotella per la distanza' },
  { id: 'sumie', dim: '3D', titolo: 'Inchiostro sumi-e',
    ispirazione: 'Ōkami, pittura a inchiostro giapponese',
    descrizione: 'Montagne e bambù dipinti a inchiostro su carta di riso. Dove passi il pennello, la vita torna.',
    tecnica: 'Densità d\'inchiostro dalla luce, aloni ai bordi delle velature, contorni a pennello di spessore variabile sfrangiati dalle fibre della carta, nebbia che scioglie la base dei monti, pennello celeste disegnato col mouse.',
    controlli: 'Trascina per girare · tieni premuto Maiusc e disegna: un cerchio nel cielo fa sorgere il sole, una linea su un albero secco lo fa fiorire' },
  { id: 'vangogh', dim: '3D', titolo: 'Pennellate',
    ispirazione: 'Vincent van Gogh, Notte stellata',
    descrizione: 'Un villaggio in 3D dipinto a olio: ogni pixel diventa una pennellata che segue la forma.',
    tecnica: 'Campo di direzioni dal tensore di struttura dell\'immagine; decine di migliaia di pennellate ancorate al mondo, in tre strati dal grosso al fine, con l\'impasto illuminato di taglio; cielo a vortici che gira piano.',
    controlli: 'Trascina per girare · rotella per lo zoom' },
  { id: 'plastilina', dim: '3D', titolo: 'Plastilina stop-motion',
    ispirazione: 'Aardman, Wallace & Gromit',
    descrizione: 'Un diorama in plastilina animato a passo uno, con le impronte delle dita e la profondità di campo da modellino.',
    tecnica: 'Impronte e ammaccature procedurali che cambiano a ogni posa, luce avvolgente da studio, animazione a 12 pose al secondo, profondità di campo da modellino.',
    controlli: 'WASD per muovere il pupazzo · trascina per girare · rotella per lo zoom' },
  { id: 'sdf', dim: '3D', titolo: 'Procedurale puro',
    ispirazione: 'Demoscene, Shadertoy',
    descrizione: 'Un mondo intero senza un solo modello: tutto è una formula calcolata pixel per pixel.',
    tecnica: 'Raymarching di campi di distanza in un solo shader: ombre morbide, occlusione ambientale, mare di nuvole, prospettiva aerea; calcolato a risoluzione ridotta che si adatta per restare fluido.',
    controlli: 'Clic e mouse per guardare · WASD per volare · Q/E giù e su · Maiusc per andare veloce' },
  { id: 'fumetto', dim: '3D', titolo: 'Pop art',
    ispirazione: 'Roy Lichtenstein, fumetti americani anni \'60',
    descrizione: 'Una scena 3D stampata come una vignetta: retini a punti, colori primari, onomatopee.',
    tecnica: 'Colori ridotti agli inchiostri di stampa, retino Ben-Day a punti allineato allo schermo, tratteggio nelle ombre, contorni spessi, onomatopee che esplodono.',
    controlli: 'WASD per muoversi · spazio per colpire · trascina per girare la visuale' },

  { id: 'hd2d', dim: '3D', titolo: 'HD-2D',
    ispirazione: 'Octopath Traveler',
    descrizione: 'Personaggi in pixel art dentro un diorama 3D, con la luce di una lanterna e la sfocatura da modellino.',
    tecnica: 'Sprite a pixel su piani rivolti alla camera, mondo 3D a texture pixelate, luci calde dei lampioni e luna fredda con ombre, profondità di campo tilt-shift a bokeh, bagliore, raggi volumetrici, lucciole e pulviscolo, grading caldo-freddo.',
    controlli: 'WASD per camminare · Q/E per ruotare la visuale' },
  { id: 'papermario', dim: '3D', titolo: 'Personaggi di carta',
    ispirazione: 'Paper Mario',
    descrizione: 'Personaggi sottili come un foglio in un mondo di cartoncino: quando si girano, si voltano come una pagina.',
    tecnica: 'Figure piatte con bordo bianco da ritaglio, un foglio a due facce che si volta come una pagina; colline di cartone ondulato, alberi piegati a V con la linguetta, nuvole appese al filo, luce morbida da lampada.',
    controlli: 'WASD per camminare · spazio per saltare · salta sullo scarabeo per appiattirlo' },

  // ───────────────────────────── 2D ─────────────────────────────
  { id: 'pixel16', dim: '2D', titolo: 'Pixel art 16 bit',
    ispirazione: 'Super Nintendo',
    descrizione: 'Un platform con fondali a parallasse e personaggi animati fotogramma per fotogramma.',
    tecnica: 'Risoluzione logica fissa ingrandita a scala intera senza filtro, cielo a bande con retino come un gradiente HDMA, sei piani di parallasse, sprite animati fotogramma per fotogramma, polvere al salto, mare animato, aloni additivi a gradini.',
    controlli: '← → per correre · spazio per saltare · schiaccia i nemici saltandoci sopra' },
  { id: 'gameboy', dim: '2D', titolo: 'Game Boy',
    ispirazione: 'Game Boy (1989), Link\'s Awakening',
    descrizione: 'Quattro sfumature di verde su uno schermo da 160×144, con la scia dei cristalli liquidi.',
    tecnica: 'Il mondo si disegna a 160×144 in quattro livelli; i cristalli liquidi cambiano lentamente e lasciano la scia; uno shader ingrandisce lo schermo con la griglia dei pixel, la loro ombra sul fondo e i bordi morbidi. Scorrimento a schermate, tre modelli di console.',
    controlli: 'Frecce o WASD per muoversi · spazio per leggere i cartelli e parlare · H cambia modello (DMG, Pocket, Light)' },
  { id: 'silhouette', dim: '2D', titolo: 'Silhouette',
    ispirazione: 'Limbo',
    descrizione: 'Un bosco in bianco e nero dove tutto è ombra, nebbia e grana di pellicola.',
    tecnica: 'Piani di alberi sempre più chiari e sfocati con la distanza, banchi di nebbia, raggi di luce, grana di pellicola, sfarfallio e vignettatura; una cassa da spingere, una tagliola e un tronco a pendolo.',
    controlli: '← → per muoversi · spazio per saltare · spingi la cassa contro la roccia per salire' },
  { id: 'riso', dim: '2D', titolo: 'Risografia',
    ispirazione: 'Stampa risograph, fanzine',
    descrizione: 'Una città stampata con due inchiostri fluo, fuori registro e con la grana della carta.',
    tecnica: 'Separazione in lastre di colore, retino a punti granuloso, sovrastampa in moltiplicazione, registro che sbanda, carta avorio.',
    controlli: 'Spazio per volare · R per ristampare' },
  { id: 'crt', dim: '2D', titolo: 'Vettoriale CRT',
    ispirazione: 'Asteroids (1979)',
    descrizione: 'Linee di luce su uno schermo vettoriale, con il bagliore e la scia del fosforo.',
    tecnica: 'Fascio gaussiano in un buffer a virgola mobile, fosforo con due persistenze (scia breve e alone lungo), punti più accesi dove il fascio si ferma, bagliore a tre scale, vetro curvo con riflessi, sfarfallio.',
    controlli: '← → per ruotare · ↑ per spingere · spazio per sparare · Maiusc per l\'iperspazio' },
  { id: 'ascii', dim: '2D', titolo: 'ASCII',
    ispirazione: 'Brogue, Dwarf Fortress',
    descrizione: 'Un sotterraneo fatto solo di lettere, illuminato da torce e fuochi che si propagano.',
    tecnica: 'Griglia di caratteri con luce colorata da ogni sorgente, campo visivo e memoria grigio-blu, acqua e lava animate, fuoco che si propaga sull\'erba cella per cella lasciando cenere, braci e fumo.',
    controlli: 'Frecce o WASD per muoversi · spazio per lanciare una fiala incendiaria · urta un braciere per rovesciarlo' },
  { id: 'quaderno', dim: '2D', titolo: 'Scarabocchi',
    ispirazione: 'Doodle Jump, quaderni di scuola',
    descrizione: 'Un gioco disegnato a penna biro su un quaderno a quadretti, con le linee che tremano.',
    tecnica: 'Ogni tratto di biro trema e si ridisegna nove volte al secondo (line boil), ripassato due volte; tratteggi a zig-zag al posto dei pieni, evidenziatore in trasparenza, quadretti, macchia di caffè.',
    controlli: '← → per muoversi · il salto è automatico' },
  { id: 'carta', dim: '2D', titolo: 'Carta ritagliata',
    ispirazione: 'Tearaway, i libri pop-up',
    descrizione: 'Un paesaggio di cartoncini sovrapposti, con le ombre fra uno strato e l\'altro.',
    tecnica: 'Strati ritagliati e strappati con l\'anima bianca sull\'orlo, fibra della carta, ombre portate che dicono la distanza fra i fogli, parallasse, pop-up che si alzano a molla, burattino a fermacampioni.',
    controlli: '← → per camminare · spazio per saltare' },
  { id: 'ukiyoe', dim: '2D', titolo: 'Ukiyo-e',
    ispirazione: 'Hokusai, La grande onda',
    descrizione: 'Una barca fra le onde, stampata come una xilografia giapponese.',
    tecnica: 'Colori piatti per matrice con il registro che sbanda, sfumature bokashi, contorni a spessore variabile come un intaglio, venatura del legno e carta di gelso.',
    controlli: '← → per remare · spazio per saltare l\'onda' },
  { id: 'mondrian', dim: '2D', titolo: 'De Stijl',
    ispirazione: 'Piet Mondrian',
    descrizione: 'Un breakout dentro una composizione di Mondrian: ogni rettangolo che rompi ridisegna il quadro.',
    tecnica: 'Suddivisione ricorsiva della tela in un albero di tagli; quando un rettangolo cade, la linea che lo separava scivola e il vicino si allarga. Pennellate e trama della tela procedurali, variante Boogie Woogie a strade gialle.',
    controlli: 'Mouse o ← → per la racchetta · spazio lancia · N nuovo quadro' },
  { id: 'outrun', dim: '2D', titolo: 'Pseudo-3D synthwave',
    ispirazione: 'Out Run (1986), estetica synthwave',
    descrizione: 'Una corsa verso un sole al neon, con la strada fatta di strisce come nelle sale giochi.',
    tecnica: 'Strada a segmenti proiettati con curve e colline finte, sprite in pixel art scalati, sole a strisce, montagne a fil di ferro, griglia al neon nel terreno, bagliore e scanline.',
    controlli: '← → per sterzare · ↑ per accelerare' },
  { id: 'vetrata', dim: '2D', titolo: 'Vetrata',
    ispirazione: 'Vetrate gotiche',
    descrizione: 'Una vetrata piombata attraversata dal sole, che getta la sua luce colorata sul pavimento.',
    tecnica: 'Tessere di vetro da diagramma di Voronoi dentro un cartone disegnato, piombature, grisaglia dipinta, bolle e venature; il sole attraversa la finestra e si proietta sul pavimento, con raggi nel pulviscolo e bagliore.',
    controlli: 'Muovi il mouse per spostare il sole · clic o spazio cambia l\'ora · N fa passare una nuvola' },
  { id: 'lttp', dim: '2D', titolo: '16 bit dall\'alto',
    ispirazione: 'The Legend of Zelda: A Link to the Past',
    descrizione: 'Un villaggio e un bosco visti dall\'alto, con l\'erba alta da tagliare, i cespugli, l\'acqua che luccica e le chiome che ti passano davanti.',
    tecnica: 'Schermo di 320×180 ingrandito a scala intera senza filtro, mappa a tessere su tre strati (pavimento, oggetti, chiome sopra il personaggio), acqua e fiori animati, ombre a mezza tinta come sul Super Nintendo, erba e cespugli da tagliare.',
    controlli: 'Frecce o WASD per muoversi · spazio per colpire con la spada o parlare' },
  { id: 'omori', dim: '2D', titolo: 'Tratto tremolante',
    ispirazione: 'Omori',
    descrizione: 'Un mondo di sogno quasi bianco, disegnato a matita e pastelli, dove le linee respirano piano come in un cartone fatto a mano.',
    tecnica: 'Ogni disegno esiste in tre varianti leggermente diverse che si alternano (line boil), tratto a matita che non si chiude, pastello che esce dai bordi con la grana del foglio, ombre a tratteggio, occhi nel buio che ti seguono.',
    controlli: 'Frecce o WASD per muoversi · spazio per interagire' },
  { id: 'vettoriale', dim: '2D', titolo: 'Flat design',
    ispirazione: 'Kurzgesagt',
    descrizione: 'Un piccolo pianeta vettoriale che gira fra il giorno e la notte.',
    tecnica: 'Forme vettoriali pulite, ombre lunghe piatte, notte a tre mezzi toni, gradienti solo sulle luci (sole, atmosfera, finestre, faro), animazioni a molla.',
    controlli: 'Trascina per ruotare il pianeta · clic per piantare un albero · ← → per ruotare' },
];
